### ISSUE TITLE
Import Error occur

### ISSUE THREAD

**Issue by GoJunHyeong** [BinahHu/DNE#2]
Thank you for the code release. I am sharing the error that occurred during the implementation process.

Traceback (most recent call last):
  File "main.py", line 34, in <module>
    from continual.split_blocks import split_config
ImportError: cannot import name 'split_config' from 'continual.split_blocks'

I checked DyTox's code, but likewise, the split_blocks function did not exist.

**Comment by BinahHu** [comment]
Thank you very much, I forgot to remove some unused codes when I simplify them. This bug has been fixed now.
